version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gadgets-heaven-api
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_PREFIX=api/v1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=gadgets_heaven
      - JWT_SECRET=your-super-secret-key-change-in-production
      - JWT_EXPIRATION=1d
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - gadgets-heaven-network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: gadgets-heaven-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gadgets_heaven
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gadgets-heaven-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  gadgets-heaven-network:
    driver: bridge
